'use client'

import { useState, useMemo } from 'react'
import { useTranslations } from 'next-intl'
import { SavingsCampaign, SavingsMilestone, db } from '@/lib/db'
import { generateId, formatARS } from '@/lib/utils'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { toast } from 'sonner'
import {
  Plus,
  Target,
  CheckCircle2,
  Calendar,
  Trash2,
  Edit,
  Wand2,
  CalendarDays,
  CalendarRange
} from 'lucide-react'

type FrequencyOption = 'weekly' | 'biWeekly' | 'monthly' | 'quarterly'

interface GeneratedMilestone {
  name: string
  targetAmount: number
  targetDate: Date
}

interface MilestonesTabProps {
  campaign: SavingsCampaign
  milestones: SavingsMilestone[]
}

export function MilestonesTab({ campaign, milestones }: MilestonesTabProps) {
  const t = useTranslations('savings')

  const [showAddDialog, setShowAddDialog] = useState(false)
  const [showDeleteDialog, setShowDeleteDialog] = useState(false)
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false)
  const [selectedMilestone, setSelectedMilestone] = useState<SavingsMilestone | null>(null)
  const [isSubmitting, setIsSubmitting] = useState(false)

  // Form state
  const [name, setName] = useState('')
  const [targetAmount, setTargetAmount] = useState('')
  const [targetDate, setTargetDate] = useState('')

  // Auto-generate state
  const [frequency, setFrequency] = useState<FrequencyOption>('monthly')
  const [replaceExisting, setReplaceExisting] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)

  // Format amount
  const formatAmount = (amount: number) => {
    if (campaign.currency === 'USD') {
      return `US$ ${amount.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
    }
    return `$ ${formatARS(amount)}`
  }

  // Format date
  const formatDate = (date: Date) => {
    return new Date(date).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    })
  }

  // Generate milestone previews based on frequency
  const generatedMilestones = useMemo((): GeneratedMilestone[] => {
    const now = new Date()
    const deadline = new Date(campaign.deadline)

    if (deadline <= now) return []

    const milestonesList: GeneratedMilestone[] = []
    let currentDate = new Date(now)

    // Get interval in days based on frequency
    const getNextDate = (date: Date, freq: FrequencyOption): Date => {
      const next = new Date(date)
      switch (freq) {
        case 'weekly':
          next.setDate(next.getDate() + 7)
          break
        case 'biWeekly':
          next.setDate(next.getDate() + 14)
          break
        case 'monthly':
          next.setMonth(next.getMonth() + 1)
          break
        case 'quarterly':
          next.setMonth(next.getMonth() + 3)
          break
      }
      return next
    }

    // Generate dates
    let milestoneNumber = 1
    currentDate = getNextDate(currentDate, frequency)

    while (currentDate < deadline) {
      milestonesList.push({
        name: `${t('milestones.autoGenerate.milestonePreview', { number: milestoneNumber })}`,
        targetDate: new Date(currentDate),
        targetAmount: 0 // Will calculate proportionally
      })
      milestoneNumber++
      currentDate = getNextDate(currentDate, frequency)
    }

    // Always add the final milestone at deadline
    milestonesList.push({
      name: `${t('milestones.autoGenerate.milestonePreview', { number: milestoneNumber })}`,
      targetDate: deadline,
      targetAmount: campaign.goalAmount
    })

    // Calculate proportional amounts
    const totalMilestones = milestonesList.length
    milestonesList.forEach((m, index) => {
      m.targetAmount = Math.round((campaign.goalAmount * (index + 1)) / totalMilestones)
    })

    return milestonesList
  }, [campaign.deadline, campaign.goalAmount, frequency, t])

  // Handle auto-generate milestones
  const handleAutoGenerate = async () => {
    if (generatedMilestones.length === 0) return

    setIsGenerating(true)

    try {
      // Delete existing milestones if requested
      if (replaceExisting && milestones.length > 0) {
        const milestoneIds = milestones.map(m => m.id!)
        await db.savingsMilestones.bulkDelete(milestoneIds)
      }

      // Create new milestones
      const startingOrder = replaceExisting ? 1 : milestones.length + 1
      const newMilestones = generatedMilestones.map((m, index) => ({
        id: generateId('sml'),
        campaignId: campaign.id!,
        name: m.name,
        targetAmount: m.targetAmount,
        targetDate: m.targetDate,
        isReached: campaign.currentAmount >= m.targetAmount,
        reachedAt: campaign.currentAmount >= m.targetAmount ? new Date() : undefined,
        order: startingOrder + index,
        createdAt: new Date()
      }))

      await db.savingsMilestones.bulkAdd(newMilestones)

      toast.success(t('milestones.autoGenerate.success', { count: generatedMilestones.length }))
      setShowAutoGenerateDialog(false)
      setReplaceExisting(false)
    } catch (error) {
      console.error('Error generating milestones:', error)
      toast.error(t('messages.error'))
    } finally {
      setIsGenerating(false)
    }
  }

  // Reset form
  const resetForm = () => {
    setName('')
    setTargetAmount('')
    setTargetDate('')
    setSelectedMilestone(null)
  }

  // Handle add/edit milestone
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!name.trim()) {
      toast.error(t('validation.milestoneNameRequired'))
      return
    }

    const amount = parseFloat(targetAmount)
    if (isNaN(amount) || amount <= 0) {
      toast.error(t('validation.milestoneAmountRequired'))
      return
    }

    if (!targetDate) {
      toast.error(t('validation.milestoneDateRequired'))
      return
    }

    setIsSubmitting(true)

    try {
      if (selectedMilestone) {
        // Update existing
        await db.savingsMilestones.update(selectedMilestone.id!, {
          name: name.trim(),
          targetAmount: amount,
          targetDate: new Date(targetDate),
          isReached: campaign.currentAmount >= amount,
          reachedAt: campaign.currentAmount >= amount ? new Date() : undefined
        })
        toast.success(t('messages.milestoneUpdated'))
      } else {
        // Add new
        const order = milestones.length + 1
        await db.savingsMilestones.add({
          id: generateId('sml'),
          campaignId: campaign.id!,
          name: name.trim(),
          targetAmount: amount,
          targetDate: new Date(targetDate),
          isReached: campaign.currentAmount >= amount,
          reachedAt: campaign.currentAmount >= amount ? new Date() : undefined,
          order,
          createdAt: new Date()
        })
        toast.success(t('messages.milestoneAdded'))
      }

      resetForm()
      setShowAddDialog(false)
    } catch (error) {
      console.error('Error saving milestone:', error)
      toast.error(t('messages.error'))
    } finally {
      setIsSubmitting(false)
    }
  }

  // Handle delete
  const handleDelete = async () => {
    if (!selectedMilestone) return

    try {
      await db.savingsMilestones.delete(selectedMilestone.id!)
      toast.success(t('messages.milestoneDeleted'))
      setShowDeleteDialog(false)
      setSelectedMilestone(null)
    } catch (error) {
      console.error('Error deleting milestone:', error)
      toast.error(t('messages.error'))
    }
  }

  // Open edit dialog
  const openEditDialog = (milestone: SavingsMilestone) => {
    setSelectedMilestone(milestone)
    setName(milestone.name)
    setTargetAmount(milestone.targetAmount.toString())
    setTargetDate(new Date(milestone.targetDate).toISOString().split('T')[0])
    setShowAddDialog(true)
  }

  return (
    <Card>
      <CardContent className="p-6">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-lg font-semibold flex items-center gap-2">
            <Target className="h-5 w-5 text-purple-500" />
            {t('milestones.title')}
          </h3>
          <div className="flex items-center gap-2">
            <Button
              onClick={() => setShowAutoGenerateDialog(true)}
              size="sm"
              variant="outline"
              className="text-purple-600 border-purple-200 hover:bg-purple-50 dark:border-purple-800 dark:hover:bg-purple-950/30"
            >
              <Wand2 className="h-4 w-4 mr-1" />
              {t('milestones.autoGenerate.button')}
            </Button>
            <Button onClick={() => { resetForm(); setShowAddDialog(true); }} size="sm">
              <Plus className="h-4 w-4 mr-1" />
              {t('milestones.addMilestone')}
            </Button>
          </div>
        </div>

        {milestones.length === 0 ? (
          <div className="text-center py-12">
            <Target className="h-12 w-12 text-gray-300 mx-auto mb-3" />
            <p className="text-gray-500 dark:text-gray-400 mb-1">
              {t('milestones.noMilestones')}
            </p>
            <p className="text-sm text-gray-400 dark:text-gray-500">
              {t('milestones.noMilestonesDescription')}
            </p>
          </div>
        ) : (
          <div className="relative">
            {/* Timeline line */}
            <div className="absolute left-4 top-0 bottom-0 w-0.5 bg-gray-200 dark:bg-gray-700" />

            <div className="space-y-4">
              {milestones.map((milestone) => {
                const progress = (campaign.currentAmount / milestone.targetAmount) * 100
                const isReached = campaign.currentAmount >= milestone.targetAmount

                return (
                  <div key={milestone.id} className="relative flex gap-4 pl-10">
                    {/* Timeline dot */}
                    <div className={`absolute left-2 w-5 h-5 rounded-full flex items-center justify-center ${
                      isReached
                        ? 'bg-green-500'
                        : 'bg-gray-300 dark:bg-gray-600'
                    }`}>
                      {isReached && <CheckCircle2 className="h-3 w-3 text-white" />}
                    </div>

                    <div className={`flex-1 p-4 rounded-lg border ${
                      isReached
                        ? 'bg-green-50 dark:bg-green-950/30 border-green-200 dark:border-green-800'
                        : 'bg-white dark:bg-gray-900 border-gray-200 dark:border-gray-700'
                    }`}>
                      <div className="flex items-start justify-between mb-2">
                        <div>
                          <h4 className="font-medium">{milestone.name}</h4>
                          <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400 mt-1">
                            <Calendar className="h-3 w-3" />
                            {formatDate(milestone.targetDate)}
                          </div>
                        </div>
                        <div className="flex items-center gap-1">
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7"
                            onClick={() => openEditDialog(milestone)}
                          >
                            <Edit className="h-3 w-3" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7 text-red-600 hover:text-red-700 hover:bg-red-50"
                            onClick={() => {
                              setSelectedMilestone(milestone)
                              setShowDeleteDialog(true)
                            }}
                          >
                            <Trash2 className="h-3 w-3" />
                          </Button>
                        </div>
                      </div>

                      <div className="flex items-center justify-between">
                        <span className="text-lg font-bold">
                          {formatAmount(milestone.targetAmount)}
                        </span>
                        {isReached ? (
                          <span className="text-sm text-green-600 dark:text-green-400 font-medium">
                            {t('milestones.reached')}
                          </span>
                        ) : (
                          <span className="text-sm text-gray-500">
                            {Math.round(progress)}%
                          </span>
                        )}
                      </div>

                      {!isReached && (
                        <div className="mt-2 h-1.5 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                          <div
                            className="h-full bg-purple-500 rounded-full transition-all"
                            style={{ width: `${Math.min(100, progress)}%` }}
                          />
                        </div>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* Add/Edit Milestone Dialog */}
        <Dialog open={showAddDialog} onOpenChange={(open) => { if (!open) resetForm(); setShowAddDialog(open); }}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>
                {selectedMilestone ? t('milestones.editMilestone') : t('milestones.addMilestone')}
              </DialogTitle>
            </DialogHeader>

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="milestoneName">{t('milestones.name')}</Label>
                <Input
                  id="milestoneName"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder={t('milestones.namePlaceholder')}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="milestoneAmount">{t('milestones.targetAmount')}</Label>
                <Input
                  id="milestoneAmount"
                  type="number"
                  value={targetAmount}
                  onChange={(e) => setTargetAmount(e.target.value)}
                  placeholder="0"
                  min="0"
                  step="0.01"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="milestoneDate">{t('milestones.targetDate')}</Label>
                <Input
                  id="milestoneDate"
                  type="date"
                  value={targetDate}
                  onChange={(e) => setTargetDate(e.target.value)}
                />
              </div>

              <div className="flex justify-end gap-3 pt-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => { resetForm(); setShowAddDialog(false); }}
                >
                  {t('form.cancel')}
                </Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting ? t('form.saving') : t('form.save')}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>

        {/* Delete Confirmation Dialog */}
        <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>{t('milestones.delete')}</AlertDialogTitle>
              <AlertDialogDescription>
                {t('milestones.deleteConfirm')}
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>{t('form.cancel')}</AlertDialogCancel>
              <AlertDialogAction onClick={handleDelete} className="bg-red-600 hover:bg-red-700">
                {t('milestones.delete')}
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>

        {/* Auto-Generate Dialog */}
        <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
          <DialogContent className="sm:max-w-2xl">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Wand2 className="h-5 w-5 text-purple-500" />
                {t('milestones.autoGenerate.title')}
              </DialogTitle>
              <DialogDescription>
                {t('milestones.autoGenerate.description')}
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-6">
              {/* Frequency Selection */}
              <div className="space-y-3">
                <Label className="text-base font-semibold">{t('milestones.autoGenerate.frequency')}</Label>
                <div className="grid grid-cols-2 gap-3">
                  {([
                    { value: 'weekly' as FrequencyOption, icon: Calendar },
                    { value: 'biWeekly' as FrequencyOption, icon: CalendarRange },
                    { value: 'monthly' as FrequencyOption, icon: CalendarDays },
                    { value: 'quarterly' as FrequencyOption, icon: Target },
                  ]).map(({ value, icon: Icon }) => (
                    <button
                      key={value}
                      type="button"
                      onClick={() => setFrequency(value)}
                      className={`p-4 rounded-xl border-2 transition-all text-left hover:shadow-md ${
                        frequency === value
                          ? 'border-purple-500 bg-purple-50 dark:bg-purple-950/30 shadow-md ring-2 ring-purple-200 dark:ring-purple-800'
                          : 'border-gray-200 dark:border-gray-700 hover:border-purple-300 bg-white dark:bg-gray-900'
                      }`}
                    >
                      <div className="flex items-center gap-3 mb-1">
                        <div className={`p-2 rounded-lg ${frequency === value ? 'bg-purple-100 dark:bg-purple-900/50' : 'bg-gray-100 dark:bg-gray-800'}`}>
                          <Icon className={`h-4 w-4 ${frequency === value ? 'text-purple-600 dark:text-purple-400' : 'text-gray-500 dark:text-gray-400'}`} />
                        </div>
                        <span className={`font-semibold ${frequency === value ? 'text-purple-700 dark:text-purple-300' : 'text-gray-700 dark:text-gray-300'}`}>
                          {t(`milestones.autoGenerate.${value}`)}
                        </span>
                      </div>
                      <p className={`text-sm ${frequency === value ? 'text-purple-600 dark:text-purple-400' : 'text-gray-500 dark:text-gray-400'}`}>
                        {t(`milestones.autoGenerate.${value}Description`)}
                      </p>
                    </button>
                  ))}
                </div>
              </div>

              {/* Replace existing option */}
              {milestones.length > 0 && (
                <div className="p-4 rounded-xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800">
                  <label className="flex items-start gap-3 cursor-pointer">
                    <Checkbox
                      checked={replaceExisting}
                      onCheckedChange={(checked) => setReplaceExisting(checked === true)}
                      className="mt-0.5"
                    />
                    <div>
                      <span className="font-medium text-amber-800 dark:text-amber-300">
                        {t('milestones.autoGenerate.replaceExisting')}
                      </span>
                      <p className="text-sm text-amber-600 dark:text-amber-400 mt-0.5">
                        {t('milestones.autoGenerate.replaceWarning')}
                      </p>
                    </div>
                  </label>
                </div>
              )}

              {/* Preview */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <Label className="text-base font-semibold">{t('milestones.autoGenerate.preview')}</Label>
                  <span className="text-sm text-purple-600 dark:text-purple-400 font-medium">
                    {t('milestones.autoGenerate.milestonesWillBeCreated', { count: generatedMilestones.length })}
                  </span>
                </div>

                <div className="max-h-60 overflow-y-auto rounded-xl border border-gray-200 dark:border-gray-700 divide-y divide-gray-200 dark:divide-gray-700">
                  {generatedMilestones.length === 0 ? (
                    <div className="p-4 text-center text-gray-500">
                      No milestones can be generated (deadline may be in the past)
                    </div>
                  ) : (
                    generatedMilestones.map((m, index) => (
                      <div key={index} className="flex items-center justify-between p-3 hover:bg-gray-50 dark:hover:bg-gray-800/50">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 rounded-full bg-purple-100 dark:bg-purple-900/50 flex items-center justify-center text-purple-600 dark:text-purple-400 text-sm font-medium">
                            {index + 1}
                          </div>
                          <div>
                            <p className="font-medium text-sm">{m.name}</p>
                            <p className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">
                              <Calendar className="h-3 w-3" />
                              {formatDate(m.targetDate)}
                            </p>
                          </div>
                        </div>
                        <span className="font-semibold text-sm">
                          {formatAmount(m.targetAmount)}
                        </span>
                      </div>
                    ))
                  )}
                </div>
              </div>

              {/* Actions */}
              <div className="flex justify-end gap-3 pt-4 border-t">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setShowAutoGenerateDialog(false)}
                  disabled={isGenerating}
                >
                  {t('form.cancel')}
                </Button>
                <Button
                  onClick={handleAutoGenerate}
                  disabled={isGenerating || generatedMilestones.length === 0}
                  className="bg-purple-600 hover:bg-purple-700"
                >
                  <Wand2 className="h-4 w-4 mr-2" />
                  {isGenerating ? t('milestones.autoGenerate.generating') : t('milestones.autoGenerate.generate')}
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  )
}
